### ISSUE TITLE
Project Part 2 Feedback

### ISSUE THREAD

**Issue by angelcache** [CMPUT301F24butter/butter-project#57]
Feedback:
UI mockups: Missing admin access screen and all the screens where the organizer/admin can manage entrants/users.
Storyboards: Some of the flows are unclear - examples, 1. in Entrant actions, how does an entrant go from the Home Screen to Scanning URL code? 2. Organizer UI - how does an organizer go from the event page to the entrants list? How is the admin moving in between different pages? It may be helpful to be obvious about where the user clicks to go from one page to another.

**Comment by Soopyman** [comment]
Response:
1. There is a button at the top right to be able to scan a QR code. This will open a new screen with a camera to scan it.
2. There is and will be a gear icon on the event page which opens to a list of options the organizer may view. One of these is the entrants list.
3. We are unsure of the admin so far. Our UI should give a basic idea of how the admin flows work.

Why is this our feedback? These are all questions which we either already have answers to, or we will have to figure out ourselves. Shouldn't the feedback be on what we are doing "good" and "bad" on?
